// Shared mock data for the hiking platform

export const routes = [
  {
    id: "wuyuan-hike",
    name: "婺源古道穿越",
    difficulty: 2 as const,
    days: 3,
    location: "江西·婺源",
    startLocation: "南昌集合",
    destination: "婺源石城",
    highlight: "千年古驿道，油菜花海与徽派古村，避开人潮的小众路线",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80",
    price: 680,
    bestSeason: "3月-4月（油菜花）、11月（秋色）",
    distance: "约38公里",
    elevation: "累计爬升约1200米",
    suitableFor: ["新手入门", "摄影爱好者", "亲子家庭"],
    description: "这是一条适合大多数人的入门级徒步路线，沿着保存完好的千年古驿道穿行于婺源的山水之间。",
    itinerary: [
      {
        day: 1,
        title: "南昌 - 婺源 - 石城",
        content: "上午从南昌出发，抵达婺源后前往石城。下午游览石城古村，傍晚在村中客栈入住。",
        meals: "含中晚餐",
        accommodation: "石城客栈（标间）",
      },
      {
        day: 2,
        title: "石城 - 篁岭 - 浙源",
        content: "清晨拍摄石城日出晨雾。上午出发徒步，经篁岭（索道上山），沿着古道前往浙源。途中穿越油菜花海。",
        meals: "含早中晚餐",
        accommodation: "浙源农家乐（多人间）",
      },
      {
        day: 3,
        title: "浙源 - 庐坑 - 返回",
        content: "上午继续徒步，参观庐坑古村（詹天佑故里），午餐后返回南昌。",
        meals: "含早中餐",
        accommodation: "无",
      },
    ],
    gearList: {
      must: ["登山背包（30L左右）", "登山鞋/防滑运动鞋", "速干衣裤", "冲锋衣", "登山杖", "防晒霜", "个人药品"],
      optional: ["防晒帽", "墨镜", "护膝", "头灯", "雨衣"],
    },
    safetyTips: ["古道部分路段较窄，注意安全", "油菜花季游客较多，提前预订住宿", "山区天气多变，备好雨具"],
    reviews: [
      { user: "山野追风", rating: 5, content: "风景绝美，古道保存得很好，领队非常专业！", date: "2026-03-15" },
      { user: "行走四方", rating: 4, content: "很适合新手的一条路线，强度不大但景色很棒。", date: "2026-02-20" },
    ],
  },
  {
    id: "yunnanshan",
    name: "云南虎跳峡徒步",
    difficulty: 3 as const,
    days: 4,
    location: "云南·丽江",
    startLocation: "丽江古城",
    destination: "香格里拉",
    highlight: "世界最深峡谷之一，金沙江咆哮而过，雪山巍峨",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?w=800&q=80",
    price: 1280,
    bestSeason: "4月-6月，9月-11月",
    distance: "约50公里",
    elevation: "累计爬升约2800米",
    suitableFor: ["进阶徒步者", "摄影爱好者", "自然探索者"],
    description: "虎跳峡是世界上最深的峡谷之一，金沙江在此劈开玉龙雪山与哈巴雪山，形成极为壮观的景象。",
    itinerary: [
      {
        day: 1,
        title: "丽江 - 虎跳峡镇",
        content: "上午从丽江出发，乘车前往虎跳峡镇，入住峡谷景区周边客栈，下午可在镇周边适应性徒步。",
        meals: "含中晚餐",
        accommodation: "虎跳峡镇客栈",
      },
      {
        day: 2,
        title: "上虎跳 - 中虎跳",
        content: "早餐后进入景区，沿栈道徒步至上虎跳观景台，拍摄金沙江咆哮场景。下午沿峡谷小道徒步至中虎跳。",
        meals: "含早中晚餐",
        accommodation: "中虎跳客栈",
      },
    ],
    gearList: {
      must: ["登山背包（45L以上）", "防水登山鞋", "冲锋衣裤", "抓绒衣", "登山杖", "防晒用品", "头灯"],
      optional: ["登山手套", "墨镜", "护膝", "睡袋内胆"],
    },
    safetyTips: ["部分路段悬崖较多，切勿靠近崖边", "雨季注意落石，必要时绕行", "高原反应需注意节奏"],
    reviews: [],
  },
  {
    id: "shilin-hike",
    name: "大理苍山洗马潭",
    difficulty: 4 as const,
    days: 2,
    location: "云南·大理",
    startLocation: "大理古城",
    destination: "苍山洗马潭",
    highlight: "高原湖泊洗马潭，360度雪山观景，云海日出",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    price: 420,
    bestSeason: "4月-10月",
    distance: "约18公里（往返）",
    elevation: "累计爬升约1600米（最高海拔3920米）",
    suitableFor: ["进阶徒步者", "高原经验者", "摄影爱好者"],
    description: "洗马潭位于苍山玉局峰与龙泉峰交接处，海拔3920米，是观赏大理坝子和洱海风光的绝佳位置。",
    itinerary: [
      {
        day: 1,
        title: "大理 - 苍山国家地质公园",
        content: "早上乘坐感通索道上山，沿木栈道徒步前往清碧溪，午餐路餐。下午继续攀登，傍晚抵达洗马潭，入住山上营地（通铺）。",
        meals: "含早晚餐（午餐路餐自理）",
        accommodation: "洗马潭营地通铺",
      },
      {
        day: 2,
        title: "洗马潭 - 大理古城",
        content: "清晨拍摄云海日出，早餐后沿原路下山，午餐后返回大理古城，自由活动。",
        meals: "含早中餐",
        accommodation: "无",
      },
    ],
    gearList: {
      must: ["登山背包（35L）", "防水登山鞋", "冲锋衣裤", "抓绒衣", "登山杖", "防晒霜", "墨镜", "头灯", "路餐（2顿）"],
      optional: ["防晒帽", "手套", "唇膏", "红景天（预防高反）"],
    },
    safetyTips: ["高原海拔较高，提前服用红景天", "山上天气多变，带好防雨装备", "高海拔徒步，避免剧烈运动"],
    reviews: [],
  },
  {
    id: "huangshan",
    name: "黄山光明顶穿越",
    difficulty: 3 as const,
    days: 2,
    location: "安徽·黄山",
    startLocation: "黄山风景区南门",
    destination: "光明顶 - 北海景区",
    highlight: "奇松怪石云海温泉，经典路线新玩法，日出日落",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=800&q=80",
    price: 380,
    bestSeason: "全年（旺季：4月-10月，赏雪：12月-2月）",
    distance: "约25公里（两日）",
    elevation: "累计爬升约1800米（最高海拔1860米）",
    suitableFor: ["有一定体力者", "摄影爱好者", "家庭出游"],
    description: "黄山是中国最著名的山脉之一，以奇松、怪石、云海、温泉四绝闻名于世。本路线串联核心景点，适合时间紧凑的游客。",
    itinerary: [
      {
        day: 1,
        title: "云谷寺 - 白鹅岭 - 光明顶",
        content: "早上从云谷寺乘索道上山，开始徒步。经白鹅岭、始信峰，抵达北海景区。下午游览狮子峰、清凉台，傍晚在光明顶观赏日落。",
        meals: "含晚餐（早中餐自理）",
        accommodation: "光明顶山庄（多人间）",
      },
      {
        day: 2,
        title: "光明顶 - 迎客松 - 南门",
        content: "清晨在光明顶观看日出（视天气情况）。早餐后经飞来石、光明顶，前往玉屏景区，观赏迎客松。乘坐玉屏索道下山。",
        meals: "含早餐（中晚餐自理）",
        accommodation: "无",
      },
    ],
    gearList: {
      must: ["登山背包（30L）", "防滑运动鞋（景区栈道）", "冲锋衣（山上风大）", "登山杖", "雨衣"],
      optional: ["防晒霜", "墨镜", "手套", "暖宝宝"],
    },
    safetyTips: ["旺季人流密集，注意跟紧队伍", "山上气候变化大，做好防雨防风准备", "索道在旺季可能排队，预留时间"],
    reviews: [],
  },
  {
    id: "qinling",
    name: "秦岭太白山穿越",
    difficulty: 5 as const,
    days: 5,
    location: "陕西·西安",
    startLocation: "西安",
    destination: "太白山拔仙台",
    highlight: "中国大陆南北分界，大白山拔仙台，中国东部最高峰",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    price: 1580,
    bestSeason: "6月-9月（夏季），10月（赏秋）",
    distance: "约80公里（全程穿越）",
    elevation: "累计爬升约3600米（最高海拔3767米）",
    suitableFor: ["资深驴友", "高海拔徒步经验者", "体能充足者"],
    description: "太白山是秦岭主峰，也是中国大陆东部最高峰。拔仙台海拔3767米，是中国南北分界线的标志性地点。这是一条真正的探险级路线。",
    itinerary: [
      {
        day: 1,
        title: "西安 - 铁甲树 - 厚畛子",
        content: "早上西安出发，乘车至铁甲树开始徒步（也可乘车至厚畛子）。夜宿厚畛�子农家乐。",
        meals: "含早晚餐（午餐路餐）",
        accommodation: "厚畛子农家乐",
      },
      {
        day: 2,
        title: "厚畛子 - 南天门",
        content: "全天徒步，从厚畛子出发，沿秦岭古道穿越原始森林，傍晚抵达南天门营地（海拔3100米）。",
        meals: "含早晚餐（午餐路餐）",
        accommodation: "南天门营地（通铺）",
      },
      {
        day: 3,
        title: "南天门 - 灵官台 - 拔仙台",
        content: "向主峰发起冲击。沿途经过灵官台、娘娘山，傍晚前抵达拔仙台脚下营地。",
        meals: "含早晚餐（午餐路餐）",
        accommodation: "拔仙台营地",
      },
      {
        day: 4,
        title: "拔仙台 - 大爷海 - 汤峪",
        content: "凌晨冲顶拔仙台观看日出（视天气）。下山经大爷海、二爷海，乘车至汤峪镇。",
        meals: "含早晚餐（午餐路餐）",
        accommodation: "汤峪镇酒店",
      },
      {
        day: 5,
        title: "汤峪 - 西安",
        content: "上午在汤峪泡温泉放松，午餐后返回西安，行程结束。",
        meals: "含早中餐",
        accommodation: "无",
      },
    ],
    gearList: {
      must: ["专业登山背包（65L以上）", "防水登山鞋", "冲锋衣裤", "抓绒衣裤", "羽绒服（高海拔必需）", "登山杖", "头灯", "睡袋（舒适温度-10℃）", "防晒霜", "墨镜", "手套", "路餐（3天）"],
      optional: ["护膝", "防晒帽", "唇膏", "红景天", "个人药品"],
    },
    safetyTips: ["高海拔徒步，充分预防高反", "恶劣天气切勿强行冲顶", "全程需结伴而行，切勿单独行动"],
    reviews: [],
  },
];

export const activities = [
  {
    id: "act-001",
    title: "周末轻徒 | 四姑娘山双桥沟入门行",
    date: "2026-04-20",
    endDate: "2026-04-22",
    location: "四川·阿坝",
    difficulty: "入门",
    participants: 12,
    maxParticipants: 15,
    price: 680,
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80",
    tags: ["周末", "入门", "摄影"],
    organizer: "踏遍山河俱乐部",
    phone: "400-888-6666",
    includes: ["全程交通", "2晚住宿", "3正2早", "专业领队", "基础保险"],
    excludes: ["个人消费", "门票（约150元）", "索道费用"],
    requirements: ["年满18周岁", "身体健康，无心脑血管疾病", "有一定运动习惯"],
    schedule: [
      { time: "Day 1 14:00", activity: "成都集合出发，乘车前往双桥沟口" },
      { time: "Day 1 18:00", activity: "入住双桥沟口客栈，晚餐" },
      { time: "Day 2 全天", activity: "双桥沟轻徒步，适应海拔，游览红杉林、布达拉峰" },
      { time: "Day 3 09:00", activity: "上午自由活动，午餐后返回成都" },
    ],
    notes: ["海拔较高（3200-3600米），注意预防高反", "双桥沟全程可乘车+徒步，适合入门", "请穿着舒适运动服装，携带防晒用品"],
    status: "open" as const,
  },
  {
    id: "act-002",
    title: "端午特辑 | 青海湖环湖徒步+露营",
    date: "2026-05-01",
    endDate: "2026-05-04",
    location: "青海·海北",
    difficulty: "进阶",
    participants: 20,
    maxParticipants: 25,
    price: 1880,
    image: "https://images.unsplash.com/photo-1504280506541-aca1b1df0bde?w=600&q=80",
    tags: ["节假日", "露营", "进阶"],
    organizer: "踏遍山河俱乐部",
    phone: "400-888-6666",
    includes: ["全程交通", "3晚露营（提供帐篷睡袋）", "4正3早", "专业领队", "户外保险"],
    excludes: ["个人消费", "门票（约90元）"],
    requirements: ["年满18周岁", "有徒步露营经验", "能承受每日20公里徒步"],
    schedule: [
      { time: "Day 1 全天", activity: "西宁集合，乘车前往青海湖西岸营地" },
      { time: "Day 2 全天", activity: "环湖徒步约20公里，途经鸟岛（季节性），湖边露营" },
      { time: "Day 3 全天", activity: "环湖徒步约25公里，橡皮山哑口，日出观景点" },
      { time: "Day 4 上午", activity: "收营，乘车返回西宁，行程结束" },
    ],
    notes: ["湖边露营，夜间气温约5-10℃，需准备保暖衣物", "高海拔（3000米以上），注意防晒和保暖", "请自备个人洗漱用品"],
    status: "open" as const,
  },
  {
    id: "act-003",
    title: "企业团建定制 | 莫干山定向穿越",
    date: "随时出发",
    endDate: "",
    location: "浙江·湖州",
    difficulty: "团建",
    participants: 8,
    maxParticipants: 50,
    price: 380,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
    tags: ["团建", "定制", "企业"],
    organizer: "踏遍山河·企业服务",
    phone: "400-888-6666",
    includes: ["活动策划", "专业领队（1:10配比）", "基础装备", "活动道具", "结业证书"],
    excludes: ["交通（可代订）", "餐饮（可代订）", "住宿（可代订）"],
    requirements: ["10人以上成团", "提前2周预约"],
    schedule: [
      { time: "上午", activity: "莫干山景区入口集合，破冰分组" },
      { time: "上午-下午", activity: "定向穿越任务（根据团队需求定制）" },
      { time: "下午", activity: "总结复盘，颁发结业证书" },
    ],
    notes: ["可定制内容：团队挑战赛、户外拓展、领导力培训等", "交通、餐饮、住宿可一站式代订", "提供往期团建案例参考"],
    status: "open" as const,
  },
  {
    id: "act-004",
    title: "新手体验营 | 杭州十里琅珰亲子徒步",
    date: "2026-04-26",
    endDate: "2026-04-26",
    location: "浙江·杭州",
    difficulty: "入门",
    participants: 15,
    maxParticipants: 20,
    price: 0,
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80",
    tags: ["亲子", "免费", "入门"],
    organizer: "踏遍山河俱乐部",
    phone: "400-888-6666",
    includes: ["专业领队", "活动道具", "简易医疗包"],
    excludes: ["交通（自驾前往）", "餐饮（自带路餐）"],
    requirements: ["6-14岁儿童需家长陪同", "身体健康，无不适合户外运动的疾病"],
    schedule: [
      { time: "09:00", activity: "杭州梅家坞集合" },
      { time: "09:00-12:00", activity: "十里琅珰亲子徒步，途中自然观察活动" },
      { time: "12:00-13:00", activity: "山顶野餐（自带路餐）" },
      { time: "13:00-15:00", activity: "龙井村游览，采茶体验（自费）" },
    ],
    notes: ["免费活动，名额有限，请珍惜名额，报名后勿随意取消", "需家长全程陪同负责孩子安全", "请穿着运动服装，携带足量饮用水"],
    status: "open" as const,
  },
];

export const safetyArticles = [
  {
    id: "safety-001",
    category: "新手入门",
    icon: "ShieldCheck",
    title: "户外徒步安全入门：出发前的10项检查",
    content: "每一次安全出行的前提，是充分的准备。这10项检查，出发前一定要过一遍...",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80",
    date: "2026-04-10",
  },
  {
    id: "safety-002",
    category: "高海拔安全",
    icon: "Mountains",
    title: "高原反应预防与应对：海拔3000米以上的生存指南",
    content: "头痛、心悸、呼吸困难——这些可能是高原反应的信号。如何预防，如何应对...",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    date: "2026-04-08",
  },
  {
    id: "safety-003",
    category: "恶劣天气",
    icon: "CloudRain",
    title: "暴雨、大风、高温：极端天气下的户外决策",
    content: "山中天气变化迅速，学会判断和决策，是保护自己的关键...",
    image: "https://images.unsplash.com/photo-1504280506541-aca1b1df0bde?w=600&q=80",
    date: "2026-04-05",
  },
  {
    id: "safety-004",
    category: "急救技巧",
    icon: "FirstAid",
    title: "户外急救必学：止血、包扎、心肺复苏",
    content: "意外发生时，每一秒都至关重要。学会这些急救技能，可能救命...",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=80",
    date: "2026-04-01",
  },
  {
    id: "safety-005",
    category: "迷路应对",
    icon: "Compass",
    title: "迷路时的正确做法：STOP原则",
    content: "迷路是大自然给徒步者的考验，STOP原则帮你冷静脱困...",
    image: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=600&q=80",
    date: "2026-03-28",
  },
  {
    id: "safety-006",
    category: "环保科普",
    icon: "Leaf",
    title: "无痕山野七原则：Leave No Trace",
    content: "我们走进山野，山野也在我们心中留下痕迹。带走一切，带走记忆，不留痕迹...",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    date: "2026-03-25",
  },
];

export const gearCategories = [
  {
    id: "core",
    name: "核心装备",
    icon: "Backpack",
    items: [
      { name: "登山背包", specs: "容量：30-80L视路线而定", price: "300-2000元", highlight: "背负系统最重要，选购时试背", tag: "必选" },
      { name: "登山鞋", specs: "建议防水 GTX 版本", price: "400-2000元", highlight: "磨合后再上山，切勿穿新鞋徒步", tag: "必选" },
      { name: "登山杖", specs: "铝合金/碳纤维，可调节", price: "100-800元", highlight: "正确使用可节省30%体力", tag: "强烈推荐" },
    ],
  },
  {
    id: "clothing",
    name: "衣物装备",
    icon: "TShirt",
    items: [
      { name: "冲锋衣", specs: "防水透气，GTX面料", price: "500-3000元", highlight: "三层穿衣法核心层，防风防雨防失温", tag: "必选" },
      { name: "速干衣裤", specs: "化纤/美利奴羊毛", price: "100-800元", highlight: "纯棉内衣禁止徒步！", tag: "必选" },
      { name: "保暖层", specs: "抓绒/排骨羽绒", price: "200-1500元", highlight: "高海拔必备，3000米以上需要羽绒服", tag: "视路线" },
    ],
  },
  {
    id: "shelter",
    name: "露营装备",
    icon: "Tent",
    items: [
      { name: "帐篷", specs: "三季帐/四季帐视季节", price: "400-3000元", highlight: "轻量化与耐用性平衡", tag: "露营必选" },
      { name: "睡袋", specs: "温标：舒适温度-5℃至-15℃", price: "200-2000元", highlight: "根据露营点最低温度选温标", tag: "露营必选" },
      { name: "防潮垫", specs: "泡沫/充气，R值>3", price: "50-500元", highlight: "隔绝地面冷气，救命装备", tag: "必选" },
    ],
  },
  {
    id: "protection",
    name: "防护装备",
    icon: "Shield",
    items: [
      { name: "登山手套", specs: "防风保暖，防滑", price: "50-300元", highlight: "防止滑坠划伤，冬季必选", tag: "视季节" },
      { name: "防晒帽", specs: "宽檐/渔夫帽", price: "30-200元", highlight: "防晒防风，防止中暑", tag: "必选" },
      { name: "防晒霜", specs: "SPF50+，防水", price: "30-100元", highlight: "高海拔紫外线极强，SPF不够需补涂", tag: "必选" },
    ],
  },
  {
    id: "electronics",
    name: "电子装备",
    icon: "Flashlight",
    items: [
      { name: "头灯", specs: "100-500流明，续航10h+", price: "80-500元", highlight: "必带！走夜路、找营地、应急全靠它", tag: "必选" },
      { name: "充电宝", specs: "10000mAh以上", price: "80-300元", highlight: "高海拔低温耗电快，多备一个", tag: "必选" },
      { name: "GPS/对讲机", specs: "有地图下载功能", price: "300-2000元", highlight: "无信号山区必备导航工具", tag: "进阶" },
    ],
  },
  {
    id: "food",
    name: "食品补给",
    icon: "CookingPot",
    items: [
      { name: "路餐", specs: "能量棒、坚果、牛肉干", price: "计重", highlight: "选择高热量小体积，每日500kcal以上", tag: "必选" },
      { name: "水袋/水壶", specs: "容量2L以上", price: "50-300元", highlight: "徒步过程随时补水", tag: "必选" },
      { name: "电解质粉", specs: "补充钠钾镁", price: "30-100元", highlight: "大量出汗后补充，防止抽筋", tag: "推荐" },
    ],
  },
];
